### ISSUE TITLE
Corrupted visuals, slow performance.

### ISSUE THREAD

**Issue by StrikerMan780** [jtrfp/terminal-recall#60] opened 2015-01-03 00:52 UTC
I'm getting insanely corrupted and flickering visuals, and slow performance. It's progressively been getting worse with each build.

Here's how it started a few builds back:
![Screenshot](http://puu.sh/dNdXC/6e5a7f0f7c.png)

Then now:
![Screenshot](http://puu.sh/dZBON/1dc1878f6f.png)
![Screenshot](http://puu.sh/dZBQv/24a2296748.png)

I'm running Windows 7 x64, with an Intel Core i5 4670k, and an NVidia GeForce GTX 560.

**Comment by cjritola** [comment] 2015-01-03 09:07
Thank you for the feedback.

I am unable to reproduce the primitive corruption issue using today's git on GT620 using driver 304.117. What driver version are you using? If your install is correct perhaps I can shift to that version and reproduce the issue.

What time-frame do these screen shots cover? Months/Weeks/Days?

Are there any interesting (red) errors in the log.html? You can ignore the "cannot load font" exception; that is a benign error caused by JavaMOD.

In the past week a lot of work has been put into getting Radeon support back up, which, due to discrepancies between brands as far as OpenGL implementations go, can result in one card's support breaking in the process of fixing another. The changes to the rendering chain lately have been significant.

I confirm it is slow as far as framerate goes, depending on resolution. 20ish at fullscreen on my end. It seems to run faster on Radeon HD at the same price point, even 3 years older. Not sure yet why this is but it may have something to do with the use of VEC4s in the engine's root memory which are optimized with most Radeon HD's 128-bit bus in mind. 

There are optimizations and removal of old framebuffer usage coming up later this week. Depending on whether or not these performance issues are bandwidth and framebuffer-related this may or may not result in a noticeable improvement.

**Comment by StrikerMan780** [comment] 2015-01-03 17:47
The timeframe is about a month and a half.

My driver version is 337.88.

**Comment by WDLmaster** [comment] 2015-01-04 00:05
There are severe graphic issues all over the place. Instead of describing every thing I've uploaded a video for you to see it. The first few seconds are level loading and initializing. But the performance is ok. No slowdowns – at least not in that video.

www.wdlmaster.de/trcl.mp4

**Comment by StrikerMan780** [comment] 2015-01-05 03:50
I get the exact issue that WDLMaster gets in the video above.

**Comment by cjritola** [comment] 2015-01-05 19:51
Yuck.

This appears to be serendipitously fixed in commit 02d00ee73671dc4dbea82430ee75a819f04456c7 while optimizing texel fetches.

Xorg-edgers "[crack pusher](https://launchpad.net/~xorg-edgers)" PPA lacks 337 but it apparently had it at one time. Interesting that they removed it. Was able to install 346.22, 343.36, 340.65, fixed some GLSL issues in the sound shader and the corruption didn't manifest until checking out prior to the above commit.

Explanation:
One or more of the involved fetches was subject to mip-mapping but the data being retrieved is not for visual use. Apparently one of nVIDIA's newer revisions resulted in GL behavior assuming mip-mapping was intended. This caused the data retrieval to become corrupt. TextureLod forces this off and behavior is as intended.

Can you pull latest and confirm fix? (expect ambient light and sky color issues)

**Comment by WDLmaster** [comment] 2015-01-06 00:52
It kinda works – but not really. Approximately 3 out of 5 Sessions freeze on startup while reading the POD files. In that case, the main window does not respond to anything. The program can only be closed by closing the console.

I just realized that videos are more useful for visual feedback than describing it so I've replaced the last video with a new one – same URL. NOTE: the end of the video was unexpected because the game crashed. So EndOfVideo == GameCrash. Don’t know how far the clipping distance in tunnels in TRCL is and at which point you show the outer map but is looks as if the crash occurred at the same time when the outer map was activated/displayed/whatever. 

I stopped in front of a bunker at one point to show lighting issues. Ground explosions seem to be rendered kinda correctly but other sprites still suffer from bad z-sorting errors (at least it looks like it) but see for yourself:

www.wdlmaster.de/trcl.mp4

The stuttering/shaking is btw not because I recorded the game but it's also present when you play normally. That issue was re-introduced lately. Sadly, I didn't check TRCL over the last 6 weeks or so, so I'm not sure since when it "returned". There was a time last year when TRCL was running silky smooth.

**Comment by cjritola** [comment] 2015-01-06 06:49
Testing in the past 6 weeks would have been a bit pointless anyway as I was fixing Radeon support which made the nVIDIA side of things go bonkers for a while.

Just confirmed the hang on startup on my machine and am analyzing thread dumps now. Not quite clear if the crash at the end was an unexpected crash or a crash resulting in the fact that player death behavior hasn't been implemented yet. (:

**Comment by WDLmaster** [comment] 2015-01-06 12:50
Yes, you're right. The crash occurs on player death. 

![](http://energyfromthorium.com/wp-content/uploads/2014/06/double-face-palm.jpg)

**Comment by StrikerMan780** [comment] 2015-01-06 18:32
After the last few commits, things are starting to return to normal. Most of the graphical glitches are gone, but the lighting seems wonky still, and explosions have the tendency to turn green, and have crazy depth issues. The framerate is slightly better too, but still a ways to go.

**Comment by cjritola** [comment] 2015-01-09 16:05
Today's git is expected to fix all but the explosion/billboard errors.

**Comment by WDLmaster** [comment] 2015-01-09 16:45
The flickering is basically gone. But the lag still persists. I think it's caused by the collision detection. I observed the console for a while, reading what appears to be the milliseconds per frame (?) and got a direct connection with the lag. As long as no or just a few collisions are active, the number stays kinda low, mostly around 20 – 30. (16 would be needed to reach 60 FPS, but at least on my system that never happens). When many projectiles and ships are around the player, the number goes through the roof (200 to 300), the FPS go down, and the lag becomes increasingly severe. 

You can test it by loading the MINE.LVL for instance. Huge lag already in briefing mode where you also hear many lasers firing. When in-game, fly away from the enemies into an empty area and watch the milliseconds for collision detection along with an increase in performance.

Has nothing to do with graphics or performance but I just found out that you can get stuck in an endless tunnel loop when a tunnel's entrance and another tunnel's exit share the same position (MINE.LVL).

**Comment by cjritola** [comment] 2015-01-09 17:41
I confirm an aggressive drop in framerate when a large number of billboards are present.

The framerate drop during briefing mode is fascinating because it doesn't go away even when the window is made very small. It features a lot of billboards since each text char is a billboard.

During regular gameplay I observe a 10FPS improvement when shrinking the window but it maxes out around 50fps and goes no further. This implies a bottleneck earlier in the pipe, possibly at object/vertex level or java. It is somewhat good to see as there are just a few more things that can be done to the deferred stage before flexibility laid out for version-2 features have to be conceded.

The method implemented in the engine for displaying billboards is known to be inefficient (93% triangle discardment per object) and there is a lot of potential to improve. Points technically aren't supported in the engine yet - each flat is an object like any other and has a similarly heavy matrix. This could be dramatically improved with point support.

This wasn't as much of a problem before as the CPU was calculating camera matrices and the GPU was hardware-culling invalid primitives early, a feature which should be put back into the engine.

A rough FPS figure can be observed in Debug->Debug States->org->jtrfp->trcl-> core -> Renderer ->FPS.  It may be wise to wait for level loading to finish as it will annoyingly explode other parts of the tree as things update.

**Comment by WDLmaster** [comment] 2015-01-09 17:53
Hm, the text billboards seem to have no impact on the frame rate (of course the have, but negligible) because if you compare MINE.LVL (many things go on in briefing-mode) with DESERT.LVL (nothing much happens in briefing mode) you'll see that DESERT.LVL has superior performance compared to MINE.LVL so it might be in fact the sprites on screen. I maximized the window (1920 x 1200) and the performance is the same as with the initial resolution.

**Comment by StrikerMan780** [comment] 2015-01-19 19:23
Is it normal that explosions are often showing up as green squares, or as nothing at all?

**Comment by cjritola** [comment] 2015-01-20 00:15
Yes, expected but not desired.

**Comment by StrikerMan780** [comment] 2015-01-20 01:44
I take it a fix is in the works.

**Comment by cjritola** [comment] 2015-01-20 02:04
Yes

**Closed** 2015-03-05 06:36 UTC
