### ISSUE TITLE
BUILD complete but, i can´t do anything!

### ISSUE THREAD

**Issue by Grondoval** [jtrfp/terminal-recall#277] opened 2022-07-14 17:31 UTC
I follow steps, build succesfully created, when i write java -jar runme.jar and enter it, it opens a Terminal Recall window, but i click on File -> Settings and nothing happen...

What should i do?

I`m using Windows 10 x64, executing CMD with admin privileges..

![abierto](https://user-images.githubusercontent.com/21977362/179045956-644dc4c5-09b6-4045-947e-fc5c83ad6d12.jpg)
.

**Comment by cjritola** [comment] 2022-07-15 04:17
When Terminal Recall starts it should have a screen similar to this:
![trcl-screen](https://user-images.githubusercontent.com/1056698/179148974-3d9a88bd-6113-43f7-bbb3-56576481cf4e.png)

In the folder containing  `RunMe.jar` there should also be a file called `log.html ` created by the program after it runs. It may have details of errors that may have occurred. They will be marked in red. Can you please share what it contains?

**Comment by Grondoval** [comment] 2022-07-15 09:41
It shows this:

[spoiler]
QueuedGL33Executor: Evaluating GL version string `4.6.0 NVIDIA 516.59`
setRunState org.jtrfp.trcl.shell.GameShellFactory$GameShell$4@5f6d6e62 old=null
setRunState org.jtrfp.trcl.shell.GameShellFactory$GameShell$5@42dc4e45 old=org.jtrfp.trcl.shell.GameShellFactory$GameShell$4@5f6d6e62
ThreadManager.GLEventListener.init()
Setting up sound system...
GPU info:
    Vendor: NVIDIA Corporation
    Renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
    Ver: 4.6.0 NVIDIA 516.59
    GLSL: 4.60 NVIDIA
System info:
    Vendor: Eclipse Adoptium
    Arch: amd64
    OS: Windows 10
    Ver:10.0
GL implementation supports 524288 array texture layers.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
compare org.jtrfp.trcl.snd.JavaSoundSystemAudioOutput to org.jtrfp.trcl.snd.JavaSoundSystemAudioOutput
compare Port Altavoces (Sound Blaster Audigy, version 0.0 to default
compare Port Altavoces (Steam Streaming Spea, version 10.0 to default
compare Port Altavoces (Steam Streaming Micr, version 10.0 to default
compare Port Realtek Digital Output (Realtek, version 10.0 to default
compare Port Micr?fono (Realtek(R) Audio), version 10.0 to default
compare Controlador primario de sonido, version Unknown Version to default
compare Altavoces (Sound Blaster Audigy Fx), version Unknown Version to default
compare Altavoces (Steam Streaming Speakers), version Unknown Version to default
compare Altavoces (Steam Streaming Microphone), version Unknown Version to default
compare Realtek Digital Output (Realtek(R) Audio), version Unknown Version to default
compare Controlador primario de captura de sonido, version Unknown Version to default
compare Micr?fono (Realtek(R) Audio), version Unknown Version to default
compare org.jtrfp.trcl.snd.JavaSoundSystemAudioOutput to org.jtrfp.trcl.snd.JavaSoundSystemAudioOutput
compare Port Altavoces (Sound Blaster Audigy, version 0.0 to Port Realtek Digital Output (Realtek, version 10.0
compare Port Altavoces (Steam Streaming Spea, version 10.0 to Port Realtek Digital Output (Realtek, version 10.0
compare Port Altavoces (Steam Streaming Micr, version 10.0 to Port Realtek Digital Output (Realtek, version 10.0
compare Port Realtek Digital Output (Realtek, version 10.0 to Port Realtek Digital Output (Realtek, version 10.0
compare Port Micr?fono (Realtek(R) Audio), version 10.0 to Port Realtek Digital Output (Realtek, version 10.0
compare Controlador primario de sonido, version Unknown Version to Port Realtek Digital Output (Realtek, version 10.0
compare Altavoces (Sound Blaster Audigy Fx), version Unknown Version to Port Realtek Digital Output (Realtek, version 10.0
compare Altavoces (Steam Streaming Speakers), version Unknown Version to Port Realtek Digital Output (Realtek, version 10.0
compare Altavoces (Steam Streaming Microphone), version Unknown Version to Port Realtek Digital Output (Realtek, version 10.0
compare Realtek Digital Output (Realtek(R) Audio), version Unknown Version to Port Realtek Digital Output (Realtek, version 10.0
compare Controlador primario de captura de sonido, version Unknown Version to Port Realtek Digital Output (Realtek, version 10.0
compare Micr?fono (Realtek(R) Audio), version Unknown Version to Port Realtek Digital Output (Realtek, version 10.0
**config path must be of level 4. Got level 2. Contents were: Port Realtek Digital Output (Realtek, version 10.0
Exception in thread "Transient Thread" java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
    at org.jtrfp.trcl.snd.SoundSystem.setOutputConfigNode(SoundSystem.java:919)
    at org.jtrfp.trcl.snd.SoundSystem.getOutputConfigNode(SoundSystem.java:837)
    at org.jtrfp.trcl.snd.SoundSystem.loadConfigAndAttachListeners(SoundSystem.java:294)
    at org.jtrfp.trcl.snd.SoundSystem.initialize(SoundSystem.java:143)
    at org.jtrfp.trcl.ext.tr.SoundSystemFactory$SoundSystemFeature.apply(SoundSystemFactory.java:57)
    at org.jtrfp.trcl.ext.tr.SoundSystemFactory$SoundSystemFeature.apply(SoundSystemFactory.java:40)
    at org.jtrfp.trcl.core.FeaturesImpl.newFeatureInstance(FeaturesImpl.java:158)
    at org.jtrfp.trcl.core.FeaturesImpl.getFeature(FeaturesImpl.java:141)
    at org.jtrfp.trcl.core.FeaturesImpl.get(FeaturesImpl.java:177)
    at org.jtrfp.trcl.core.FeaturesImpl.init(FeaturesImpl.java:107)
    at org.jtrfp.trcl.core.FeaturesImpl.newFeatureInstance(FeaturesImpl.java:159)
    at org.jtrfp.trcl.core.FeaturesImpl.getFeature(FeaturesImpl.java:141)
    at org.jtrfp.trcl.core.FeaturesImpl.get(FeaturesImpl.java:177)
    at org.jtrfp.trcl.core.FeaturesImpl.init(FeaturesImpl.java:107)
    at org.jtrfp.trcl.core.Features.init(Features.java:56)
    at org.jtrfp.trcl.flow.RunMe$1.run(RunMe.java:71)
    at org.jtrfp.trcl.core.DefaultKeyedExecutor.executeAllFromThisThread(DefaultKeyedExecutor.java:64)
    at org.jtrfp.trcl.flow.TransientExecutor$TransientThread.run(TransientExecutor.java:43)**
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
Creating GL Texture...
...Done.
WindowClosing...
WindowClosing...
WindowClosing...

[/spoiler]

**Comment by cjritola** [comment] 2022-07-16 06:43
I may have figured out how to reproduce and isolate this bug. Will post a fix in a few days.

**Comment by cjritola** [comment] 2022-07-20 00:49
Thanks for the bug report. Fixes have been committed. To update your source code, please run `git pull` from the project's root folder (the one where you ran `mvn clean install`). After git updates the source code, re-run `mvn clean install` to rebuild the project and try it out in the `target` subfolder with `java -jar RunMe.jar`

If it still fails, try deleting the `settings.config.trcl.xml` if it exists in your user's home directory, or whatever user used to run the `java -jar RunMe.jar` command. If it still, still fails, please return with log.html output if convenient.

**DETAIL:**
The audio device tree on some systems has sub-devices which feature no ports or formats, leaving their leaf nodes with depths less than 4. The filtering mechanism to ignore these was not sufficient. Consequently, invalid nodes were submitted to SoundSystem on startup, throwing unchecked exceptions, which then aborted the Transient thread.

This may have then caused the startup sequence to abort. Was not able to reproduce the failure to show a home screen. Although this bug is genuine, there may be another underlying bug or incompatibility which is causing the home screen failure.

Also, DummyAudioDriver was re-introduced, such that if a target system has no usable audio outputs, the dummy driver will take place of it and allow the program to continue running.

**Comment by Grondoval** [comment] 2022-07-21 21:17
Cool! Now all runs well! Thank you very much! 👍

**Comment by cjritola** [comment] 2022-07-22 00:34
Glad to hear. Closing issue...

**Closed by cjritola** 2022-07-22 00:34 UTC
Labels: Bug
