### ISSUE TITLE
Joystick configuration option not displaying in settings

### ISSUE THREAD

**Issue by nbarros8** [jtrfp/terminal-recall#248] opened 2018-06-14 22:06 UTC
Joystick: Logitech Extreme 3D (USB)

System info:
        Vendor: Oracle Corporation
        Arch: amd64
        OS: Windows 10
        Ver:10.0

![image](https://user-images.githubusercontent.com/40279565/41440638-e983a148-6ff4-11e8-92ee-83a270614b01.png)
![image](https://user-images.githubusercontent.com/40279565/41440698-3aef2d86-6ff5-11e8-840c-e12ba46d8410.png)

**Comment by cjritola** [comment] 2018-06-18 20:16
This may be related to https://github.com/jinput/jinput/issues/16 . I have upgraded the jInput version used to 2.0.7, which may solve the issue. 

If issue persists, please check log.html in Terminal Recalls's base directory (not target) for Exceptions and their stacktraces highlighted in red, approximately a dozen lines long and paste them for me to evaluate in hopes of isolating the problem.

**Comment by nbarros8** [comment] 2018-06-19 16:12
Unfortunately it did not resolve.

Here are the exceptions:

java.lang.NullPointerException
    at net.java.games.input.RawMouse$Button.(RawMouse.java:197)
    at net.java.games.input.RawMouseInfo.createControllerFromDevice(RawMouseInfo.java:83)
    at net.java.games.input.RawInputEnvironmentPlugin.createControllersFromDevices(RawInputEnvironmentPlugin.java:160)
    at net.java.games.input.RawInputEnvironmentPlugin.enumControllers(RawInputEnvironmentPlugin.java:176)
    at net.java.games.input.RawInputEnvironmentPlugin.(RawInputEnvironmentPlugin.java:123)
    at net.java.games.input.DirectAndRawInputEnvironmentPlugin.(DirectAndRawInputEnvironmentPlugin.java:46)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.base/java.lang.Class.newInstance(Unknown Source)
    at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:160)
    at org.jtrfp.trcl.ctl.GamepadInputDeviceServiceFactory$GamepadInputDeviceService.(GamepadInputDeviceServiceFactory.java:65)
    at org.jtrfp.trcl.ctl.GamepadInputDeviceServiceFactory.newInstance(GamepadInputDeviceServiceFactory.java:208)
    at org.jtrfp.trcl.ctl.GamepadInputDeviceServiceFactory.newInstance(GamepadInputDeviceServiceFactory.java:38)
    at org.jtrfp.trcl.core.FeaturesImpl.newFeatureInstance(FeaturesImpl.java:148)
    at org.jtrfp.trcl.core.FeaturesImpl.getFeature(FeaturesImpl.java:137)
    at org.jtrfp.trcl.core.FeaturesImpl.get(FeaturesImpl.java:172)
    at org.jtrfp.trcl.core.FeaturesImpl.init(FeaturesImpl.java:105)
    at org.jtrfp.trcl.core.FeaturesImpl.newFeatureInstance(FeaturesImpl.java:154)
    at org.jtrfp.trcl.core.FeaturesImpl.getFeature(FeaturesImpl.java:137)
    at org.jtrfp.trcl.core.FeaturesImpl.get(FeaturesImpl.java:172)
    at org.jtrfp.trcl.core.FeaturesImpl.init(FeaturesImpl.java:105)
    at org.jtrfp.trcl.core.Features.init(Features.java:55)
    at org.jtrfp.trcl.flow.RunMe$1.run(RunMe.java:71)
    at org.jtrfp.trcl.core.DefaultKeyedExecutor.executeAllFromThisThread(DefaultKeyedExecutor.java:64)
    at org.jtrfp.trcl.flow.TransientExecutor$TransientThread.run(TransientExecutor.java:43)

**Comment by cjritola** [comment] 2018-06-29 03:02
Attempted fixes were committed for bug #247 and #248. At your convenience please let me know if the address the problems.

**Comment by nbarros8** [comment] 2018-06-29 15:31
Unfortunately the issues persists, is there any additional information I may provide to help?

**Comment by cjritola** [comment] 2018-07-01 07:19
Thanks for your patience. Some questions about your gaming rig: 
- What make/model of mouse(s) are you using? 
- Do you have any special mouse emulations running, such as gaming keyboards with mouse shortcuts, mouse macro programs, etc running which could potentially be creating an emulated/virtual mouse?
- If you have any of these, does the issue resolve if you run Terminal Recall after removing them?

I am curious because the part which is tripping up may be where jInput sees more mouse buttons than expected. (>32). Although Terminal Recall doesn't use jInput for mouse input, jInput iterates through all devices before presenting them to Terminal Recall, including mouse. Terminal Recall then ignores the mouse. jInput is tripping up internally when evaluating the mouse.

**Comment by nbarros8** [comment] 2018-07-03 14:05
I am using a Corsair Harpoon, but I don't have any specific mouse software.
My keyboard, mouse and joystick run solely on the built-in windows drivers.
Actually I hadn't even noticed that the mouse didn't work within the game,
since I was focused on getting the joystick to work.

**Comment by cjritola** [comment] 2021-12-11 23:46
This may be caused by a hanging instance of Terminal Recall:
https://forums.duke4.net/topic/5787-terminal-velocity/page__view__findpost__p__276134

... workaround is to make sure a previously-run instance is force-closed.

**Closed by cjritola** 2021-12-11 23:46 UTC
Labels: Bug, Windows, Input/Control
